name: Java Quality Outreach
on:
  schedule:
    - cron: 0 22 * * *

jobs:
  db2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ 15, 16 ]
    name: Db2 - Java ${{ matrix.feature }}
    steps:
      - name: Checkout core repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: debezium/debezium
          path: core
      - name: Checkout Db2 connector
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: db2
      - name: Setup OpenJDK
        uses: sormuras/download-jdk@v1
        id: jdk
        with:
          feature: ${{ matrix.feature }}
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ steps.jdk.outputs.version }}
          jdkFile: ${{ steps.jdk.outputs.file }}
      - name: Maven build core
        run: mvn clean install -f core/pom.xml -DskipTests -DskipITs -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
      - name: Maven build Db2
        run: mvn clean install -f db2/pom.xml -Passembly -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
